# Generated by Django 2.1 on 2019-11-26 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='asd',
            field=models.TextField(default='yo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tile',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
